# -*- coding: utf-8 -*-
import pathlib

path = pathlib.Path(r"c:\Users\conde\Desktop\GUIA VS\index.html")
s = path.read_text(encoding="utf-8")

pairs = [
    ('00 · Resumen', '00 · Overview'),
    ('Ubicación y logística', 'Location & logistics'),
    ('Dirección', 'Address'),
    ('Comunidad con seguridad privada 24 hrs', 'Gated community with 24-hour private security'),
    ('Estacionamiento', 'Parking'),
    ('2 autos · se entrega control de garage', '2 cars · garage remote provided'),
    ('Entrada principal', 'Main entrance'),
    ('Acceso de huéspedes por entrada frontal', 'Guest access via front entrance'),
    ('Entrada de servicio', 'Service entrance'),
    ('Personal y proveedores autorizados', 'Staff and authorized vendors only'),
    ('[ Foto: Entrada principal y fachada ]', '[ PHOTO: Main entrance & facade ]'),
    ('01 · Contactos y servicios', '01 · Contacts & services'),
    ('"Recibirte en Villa Sera es un honor. Esta casa es tuya durante tu estancia — y mi equipo está aquí para coordinar lo que necesites con calma y prontitud."',
     '"Hosting you at Villa Sera is a privilege. This home is yours for your stay — and my team is here to coordinate what you need with calm and prompt care."'),
    ('Coordinación general y soporte técnico. Enfoque diurno y asistencia oportuna; disponible para prioridades e imprevistos.',
     'General coordination and technical support. Daytime focus with timely assistance; available for priorities and urgent needs.'),
    ('Cocina personalizada', 'Personalized dining'),
    ('Menús con ingredientes de Baja: desayunos, comidas familiares o cenas de celebración.',
     'Baja-inspired menus: slow breakfasts, family lunches, or celebration dinners.'),
    ('Vía Marlon', 'Via Marlon'),
    ('Camas, detalles y el orden que invita a relajarse en cada suite.',
     'Beds, details, and the order that helps you unwind in every suite.'),
    ('Concierge pre-arrival:', 'Pre-arrival concierge:'),
    ('Antes o durante tu estancia, Marlon coordina súper (groceries a precio de costo con recibo), transportación, yates, masajes, reservas y experiencias — un solo mensaje basta.',
     'Before or during your stay, Marlon coordinates groceries (at cost with receipt), transportation, yachts, massages, reservations, and experiences — one message is enough.'),
    ('02 · La villa', '02 · The villa'),
    ('Distribución y suites', 'Layout & suites'),
    ('Piso principal para convivir; nivel inferior para descanso, media, gimnasio y playa privada.',
     'Main level for gathering; lower level for rest, media, gym, and private beach.'),
    ('alt="Terraza y alberca"', 'alt="Terrace and pool"'),
    ('[ Foto: Estancia principal / áreas comunes ]', '[ PHOTO: Main living area / common spaces ]'),
    ('Piso principal', 'Main level'),
    ('Sala de doble altura', 'Double-height living room'),
    ('con vista al Mar de Cortés', 'with Sea of Cortés views'),
    ('Comedor', 'Dining room'),
    ('para 8 personas', 'seats 8'),
    ('Cocina principal', 'Main kitchen'),
    ('equipada para montaje profesional', 'equipped for professional setup'),
    ('Lavandería', 'Laundry room'),
    ('en el mismo nivel', 'on the same level'),
    ('cama King Size, terraza con vista al mar, tina, regadera y walk-in closet',
     'King bed, terrace with ocean view, tub, shower, and walk-in closet'),
    ('Sala principal', 'Main living room'),
    ('doble altura, TCL 55" con Fire TV Stick, bar y comedor para 8',
     'double height, 55" TCL with Fire TV Stick, bar, and dining for 8'),
    ('alt="Interior Villa Sera"', 'alt="Villa Sera interior"'),
    ('Nivel inferior · Suites y media', 'Lower level · Suites & media'),
    ('Recámara 2:', 'Bedroom 2:'),
    ('Recámara 3:', 'Bedroom 3:'),
    ('Recámara 4:', 'Bedroom 4:'),
    ('cama King Size', 'King bed'),
    ('cama Queen Size', 'Queen bed'),
    ('Cuarto de TV:', 'TV room:'),
    ('Smart TV TCL 55" con Fire TV Stick (premium y canales en vivo).',
     '55" TCL smart TV with Fire TV Stick (premium apps and live channels).'),
    ('Sofá cama', 'Sofa bed'),
    ('sábanas y ropa de cama complementaria en el clóset del lado izquierdo al entrar.',
     'sheets and extra bedding in the closet on the left as you enter.'),
    ('Pantry (acceso restringido):', 'Pantry (restricted access):'),
    ('Al entrar desde la cochera, a la derecha está el pantry de la casa. Se mantiene cerrado con llave y',
     'When entering from the garage, the house pantry is on the right. It stays locked and'),
    ('no hay acceso para huéspedes', 'guests do not have access'),
    ('Terraza y alberca', 'Terrace & pool'),
    ('Alberca infinita 1.2–1.8 m con vista al Arco, splash pool, comedor exterior para 8, asador Weber y Sonos.',
     'Infinity pool 1.2–1.8 m with Arch views, splash pool, outdoor dining for 8, Weber grill, and Sonos.'),
    ('Gimnasio', 'Gym'),
    ('Caminadora con vista al mar, pesas y tapete de yoga. Siempre cubrir la banda tras cada uso.',
     'Treadmill with ocean view, weights, and yoga mat. Always cover the belt after each use.'),
    ('Cocina de alberca', 'Pool kitchen'),
    ('Cocina 2 completa: refrigerador, tarja y trastes independientes. Carbón y aditamentos del Weber se guardan aquí.',
     'Full Pool Kitchen 2: fridge, sink, and separate dishware. Weber charcoal and accessories are stored here.'),
    ('Mantenimiento', 'Maintenance'),
    ('Jardines: martes · Alberca: viernes · Limpieza profunda: a solicitud ($60 USD, 24 h de aviso).',
     'Gardens: Tuesdays · Pool: Fridays · Deep clean: on request ($60 USD, 24-hour notice).'),
    ('03 · Sistemas de la casa', '03 · Property systems'),
    ('WiFi, TV, Sonos, generador y lavandería', 'WiFi, TV, Sonos, generator & laundry'),
    ('Red WiFi', 'WiFi network'),
    ('Contraseña', 'Password'),
    ('Router:', 'Router:'),
    ('En el mueble de la cocina principal, arriba de la cafetera Nespresso. Si falla la red: desconecta 30 segundos y vuelve a conectar — se restaura en 1–2 min.',
     'In the main kitchen cabinet, above the Nespresso machine. If the network fails: unplug for 30 seconds and reconnect — restores in 1–2 min.'),
    ('Planta de emergencia:', 'Backup generator:'),
    ('Ante un apagón se activa sola y respalda el piso superior (master, cocina, sala).',
     'During a power outage it starts automatically and backs up the upper level (master, kitchen, living room).'),
    ('Los AC de recámaras 2, 3, 4 y cuarto TV no se energizan con el generador',
     'AC units in bedrooms 2, 3, 4, and the TV room do not run on generator power'),
    ('diseño intencional para cuidar la carga.', 'by design to protect the electrical load.'),
    ('Lavandería · Torre LG', 'Laundry · LG tower'),
    ('Torre vertical lavado/secado LG (color negro) en la lavandería. Detergente en estante superior. Ciclo Normal para ropa diaria; secado en ciclo estándar. Cecilia puede asistir — avisa con anticipación.',
     'Black LG washer/dryer tower in the laundry room. Detergent on the upper shelf. Normal cycle for daily laundry; standard dry cycle. Cecilia can assist — please give advance notice.'),
    ('Televisiones (todas TCL Smart TV 55")', 'Televisions (all 55" TCL smart TVs)'),
    ('TCL 55" smart ·', '55" TCL smart ·'),
    ('en HDMI (canales en vivo + Netflix, Prime, YouTube, etc.) · controles TCL y Fire en mesa de centro',
     'on HDMI (live TV + Netflix, Prime, YouTube, etc.) · TCL and Fire remotes on the coffee table'),
    ('Suite master', 'Master suite'),
    ('apps integradas (Netflix, YouTube, Prime…) · inicia sesión con tu cuenta',
     'built-in apps (Netflix, YouTube, Prime…) · sign in with your account'),
    ('Cuartos 2 y 3', 'Bedrooms 2 & 3'),
    ('Cuarto de TV', 'TV room'),
    ('(premium y canales en vivo) · sofá cama · sábanas en clóset izquierdo al entrar',
     '(premium apps and live channels) · sofa bed · sheets in left closet on entry'),
    ('Sala principal — Fire TV Stick (canales y apps)', 'Living room — Fire TV Stick (live TV & apps)'),
    ('Enciende la TCL y elige el HDMI del Fire TV', 'Turn on the TCL and select Fire TV HDMI'),
    ('Con el control de la televisión, enciende y selecciona la entrada',
     'With the TV remote, power on and select the'),
    ('donde está el Fire TV Stick (suele decir "Fire TV" o HDMI1). Si ves la antena/cable, cambia de fuente hasta ver el menú del Fire.',
     'where the Fire TV Stick is plugged in (usually "Fire TV" or HDMI1). If you see antenna/cable, switch sources until the Fire menu appears.'),
    ('Usa el control del Fire TV', 'Use the Fire TV remote'),
    ('El control pequeño negro controla el Stick. Botón', 'The small black remote controls the Stick. The'),
    ('(Inicio) siempre te regresa al menú principal. Si no responde, comprueba las pilas o apunta al televisor.',
     '(Home) button always returns to the main menu. If unresponsive, check batteries or aim at the TV.'),
    ('Ver canales en vivo', 'Watch live TV'),
    ('En la pantalla de inicio, baja hasta', 'On the home screen, scroll to'),
    ('"Tus apps y canales"', '"Your apps & channels"'),
    ('o la fila de aplicaciones. Abre la app de', 'or the apps row. Open the'),
    ('TV en vivo / lista de canales', 'live TV / channel list'),
    ('(ya está configurada). Espera a que cargue la guía; la primera vez puede tardar unos segundos.',
     '(already set up). Wait for the guide to load; the first time may take a few seconds.'),
    ('Navegar canales', 'Browse channels'),
    ('Con las', 'Use the'),
    ('flechas', 'arrow keys'),
    ('elige canal o categoría; botón central', 'to choose a channel or category; press'),
    ('para ver.', 'to watch.'),
    ('Atrás', 'Back'),
    ('(←) sube un nivel. Si la imagen se congela, mantén el botón', '(←) goes up one level. If the picture freezes, hold'),
    ('Inicio', 'Home'),
    ('y cierra la app, o desenchufa el Fire TV 10 s y vuelve a conectar.',
     'and close the app, or unplug the Fire TV for 10 s and reconnect.'),
    ('Netflix, Prime, YouTube…', 'Netflix, Prime, YouTube…'),
    ('Ábrelos desde el inicio del Fire TV o con el micrófono del control:',
     'Open them from Fire TV home or with the remote mic:'),
    ('"Alexa, abrir Netflix"', '"Alexa, open Netflix"'),
    ('(si el control tiene micrófono). Usa tu propia cuenta donde haga falta.',
     '(if the remote has a microphone). Use your own account where required.'),
    ('Otras habitaciones (TCL smart):', 'Other rooms (TCL smart):'),
    ('Abre Netflix, YouTube, Prime, etc. desde el control. En la misma red',
     'Open Netflix, YouTube, Prime, etc. from the TV remote. On the same'),
    ('red, muchas TCL permiten', 'network, many TCL TVs support'),
    ('o duplicar pantalla desde el celular.', 'or screen mirroring from your phone.'),
    ('Audio Sonos:', 'Sonos audio:'),
    ('App Sonos o AirPlay directo desde Spotify/Apple Music. Bocinas en terraza, sala, master y cocina — ver página 07.',
     'Sonos app or direct AirPlay from Spotify/Apple Music. Speakers on terrace, living room, master, and kitchen — see page 07.'),
    ('¿Problemas con el WiFi?', 'WiFi issues?'),
    ('Reinicia el router (ubicación arriba). Si persiste, contacta a Marlon.',
     'Restart the router (location above). If it persists, contact Marlon.'),
    ('Cuentas de streaming:', 'Streaming accounts:'),
    ('Inicia sesión en tu Netflix, Disney+, Prime u otras en cada TV. Recuerda',
     'Sign in to Netflix, Disney+, Prime, or others on each TV. Remember to'),
    ('cerrar sesión', 'sign out'),
    ('al hacer check-out.', 'at check-out.'),
    ('04 · Clima', '04 · Climate'),
    ('Sistema de Aire Acondicionado', 'Air conditioning'),
    ('Display A · Bar / Áreas comunes', 'Display A · Bar / common areas'),
    ('ZONA 01 · ÁREAS PRINCIPALES', 'ZONE 01 · MAIN AREAS'),
    ('● FRÍO', '● COOL'),
    ('Frío', 'Cool'),
    ('Calor', 'Heat'),
    ('Ventilador', 'Fan'),
    ('VENTILADOR · AUTO', 'FAN · AUTO'),
    ('Cubre:', 'Covers:'),
    ('Cocina principal · Sala · Comedor · Pasillo de entrada',
     'Main kitchen · Living room · Dining room · Entry hallway'),
    ('Termostato digital al', 'Digital thermostat on the'),
    ('lado izquierdo del bar', 'left side of the bar'),
    ('Sugerido:', 'Suggested:'),
    ('modo Cool, ventilador Auto.', 'Cool mode, fan Auto.'),
    ('Display B · Suite Master', 'Display B · Master suite'),
    ('ZONA 02 · SUITE MASTER', 'ZONE 02 · MASTER SUITE'),
    ('VENTILADOR · BAJO', 'FAN · LOW'),
    ('Recámara master · Baño · Walk-in closet', 'Master bedroom · Bathroom · Walk-in closet'),
    ('Termostato en la', 'Thermostat on the'),
    ('pared frente a la cama', 'wall facing the bed'),
    ('modo Cool.', 'Cool mode.'),
    ('Mini-splits independientes', 'Independent mini-splits'),
    ('Recámaras 2 y 3:', 'Bedrooms 2 & 3:'),
    ('controles en burós de noche.', 'remotes on nightstands.'),
    ('Recámara 4:', 'Bedroom 4:'),
    ('control dentro del cajón del buró — modo copo de nieve para frío.',
     'remote inside nightstand drawer — snowflake mode for cooling.'),
    ('control colgado en la pared junto a la puerta.', 'remote hanging on the wall by the door.'),
    ('Baterías de repuesto en cajón de cocina. Apunta el control hacia la unidad.',
     'Spare batteries in kitchen drawer. Aim the remote at the unit.'),
    ('Apaga el AC', 'Turn off AC'),
    ('al salir del cuarto o de la villa.', 'when leaving the room or the villa.'),
    ('Confort sin AC:', 'Comfort without AC:'),
    ('Todos los cuartos tienen mosquiteros. Si prefieres apagar el aire y dormir escuchando las olas del mar, cierra el mosquitero y disfruta la brisa.',
     'All bedrooms have mosquito nets. If you prefer to turn off the AC and sleep to the sound of the waves, close the net and enjoy the breeze.'),
    ('05 · Audio', '05 · Audio'),
    ('Sonos — Música en Toda la Villa', 'Sonos — music throughout the villa'),
    ('3 pasos para tener música en toda la villa', '3 steps to fill the villa with music'),
    ('Descarga la app Sonos', 'Download the Sonos app'),
    ('Gratis en App Store y Google Play — abajo puedes escanear el QR de tu tienda. ¿Ya la tienes? Salta al paso 2.',
     'Free on the App Store and Google Play — scan the QR below for your store. Already have it? Skip to step 2.'),
    ('Conéctate a VillaSera_Guest', 'Connect to VillaSera_Guest'),
    ('Tu teléfono debe estar en la misma red que las bocinas. La app descubre todos los altavoces automáticamente.',
     'Your phone must be on the same network as the speakers. The app discovers all speakers automatically.'),
    ('Elige cuartos y reproduce', 'Choose rooms and play'),
    ('Selecciona uno o varios cuartos. Controla el volumen por zona. Reproduce desde Spotify, Apple Music, Tidal o cualquier fuente.',
     'Select one or more rooms. Control volume by zone. Play from Spotify, Apple Music, Tidal, or any source.'),
    ('Descarga la app — escanea con la cámara', 'Get the app — scan with your camera'),
    ('alt="Código QR: Sonos en App Store"', 'alt="QR code: Sonos on App Store"'),
    ('alt="Código QR: Sonos en Google Play"', 'alt="QR code: Sonos on Google Play"'),
    ('Ubicación de bocinas', 'Speaker locations'),
    ('Terraza principal y alberca', 'Main terrace and pool'),
    ('Bocinas exteriores impermeables. Al 50% de volumen se escucha perfectamente en toda la terraza.',
     'Weatherproof outdoor speakers. At 50% volume they sound great across the terrace.'),
    ('Par estéreo completo. También funciona como soundbar con el televisor vía AirPlay.',
     'Full stereo pair. Also works as a soundbar with the TV via AirPlay.'),
    ('Bocina de mesa de noche. Ideal para música ambiental y playlists para dormir.',
     'Bedside speaker. Ideal for ambient music and sleep playlists.'),
    ('Cocina y comedor', 'Kitchen and dining'),
    ('Perfecta para cocinar y cenas. Vinculada al grupo de sala por default.',
     'Perfect for cooking and dinners. Linked to the living room group by default.'),
    ('Sin app — usa AirPlay directamente', 'No app — use AirPlay directly'),
    ('Abre Spotify o Apple Music', 'Open Spotify or Apple Music'),
    ('Confirma que estás en la WiFi VillaSera_Guest.', 'Confirm you are on VillaSera_Guest WiFi.'),
    ('Toca el ícono AirPlay', 'Tap the AirPlay icon'),
    ('El triángulo con círculos en Spotify, o el ícono de bocina en Apple Music.',
     'The triangle with circles in Spotify, or the speaker icon in Apple Music.'),
    ('Selecciona una bocina Villa Sera', 'Select a Villa Sera speaker'),
    ('Elige Terraza, Sala o cualquier cuarto. La música empieza al instante.',
     'Choose Terrace, Living Room, or any room. Music starts instantly.'),
    ('Sugerencia', 'Tip'),
    ('Pide a Marlon la lista de reproducción Villa Sera en Spotify — pensada para atardeceres en la terraza, mañanas en la alberca y noches frente al Mar de Cortés. Si prefieres la playa, Cecilia puede conseguirte bocinas Bluetooth portátiles.',
     'Ask Marlon for the Villa Sera Spotify playlist — made for terrace sunsets, pool mornings, and nights facing the Sea of Cortés. Prefer the beach? Cecilia can arrange portable Bluetooth speakers.'),
    ('07 · Gimnasio y playa', '07 · Gym & beach'),
    ('Caminadora — Uso y Cuidado', 'Treadmill — use & care'),
    ('alt="Caminadora en terraza con vista al Mar de Cortés"', 'alt="Treadmill on terrace overlooking the Sea of Cortés"'),
    ("La caminadora de Villa Sera da directamente al Mar de Cortés — siempre tapa la banda después de usar.",
     "Villa Sera's treadmill faces the Sea of Cortés directly — always cover the belt after use."),
    ('Cubierta protectora — obligatorio:', 'Protective cover — required:'),
    ('El salitre del mar daña la banda y los rieles. Coloca la cubierta impermeable inmediatamente después de cada uso. Atomizador con agua y jabón neutro en el estante — rocía banda y rieles, limpia con trapo y cubre.',
     'Sea salt damages the belt and rails. Place the waterproof cover immediately after every use. Spray bottle with water and mild soap on the shelf — spray belt and rails, wipe, and cover.'),
    ('Antes de usar', 'Before use'),
    ('Retira la cubierta', 'Remove the cover'),
    ('Levanta la cubierta protectora y dóblala. Colócala a un lado o en el estante del equipo.',
     'Lift the protective cover and fold it. Set it aside or on the equipment shelf.'),
    ('Enciende en la consola', 'Power on at the console'),
    ('Presiona el botón de encendido en la consola principal. La pantalla se iluminará en 2–3 segundos.',
     'Press the power button on the main console. The screen lights up in 2–3 seconds.'),
    ('Coloca el clip de seguridad', 'Attach the safety clip'),
    ('Engancha el clip rojo de emergencia a tu ropa. Si te caes, detiene la banda automáticamente.',
     'Clip the red emergency stop to your clothing. If you fall, it stops the belt automatically.'),
    ('Usa los controles', 'Use the controls'),
    ('Start/Stop para iniciar y detener · ▲▼ para velocidad · Incline para inclinación. Los botones están marcados en la consola.',
     'Start/Stop to begin and stop · ▲▼ for speed · Incline for grade. Buttons are labeled on the console.'),
    ('Después de usar — obligatorio', 'After use — required'),
    ('Apaga el equipo', 'Power off'),
    ('Presiona Stop y luego el botón de apagado. Espera que la banda se detenga completamente.',
     'Press Stop then the power button. Wait until the belt stops completely.'),
    ('Aplica el atomizador', 'Apply the spray'),
    ('Solución de agua y jabón neutro en el atomizador del estante. Rocía banda y rieles para eliminar sudor y sal.',
     'Water and mild soap solution in the shelf spray bottle. Spray belt and rails to remove sweat and salt.'),
    ('Limpia con el trapo', 'Wipe with the cloth'),
    ('Pasa el trapo por la banda y rieles. Deja airear 1 minuto.', 'Wipe the belt and rails. Let air dry for 1 minute.'),
    ('Coloca la cubierta', 'Replace the cover'),
    ('Siempre cubre la caminadora al terminar.', 'Always cover the treadmill when finished.'),
    ('El salitre del mar penetra aunque no se vea y deteriora la banda con el tiempo.',
     'Sea salt penetrates even when invisible and damages the belt over time.'),
    ('05 · Cocina y servicios', '06 · Kitchen & services'),
    ('Cocina, agua y servicios', 'Kitchen, water & services'),
    ('Plomería sanitaria:', 'Plumbing:'),
    ('Prohibido tirar toallitas húmedas (baby wipes) o productos higiénicos al inodoro. Usa los botes de basura obligatoriamente.',
     'Do not flush wet wipes (baby wipes) or hygiene products down the toilet. Use trash bins only.'),
    ('alt="Cocina principal de Villa Sera"', 'alt="Villa Sera main kitchen"'),
    ('Máquina Nespresso', 'Nespresso machine'),
    ('En el mostrador (router WiFi arriba de esta cafetera). Cápsulas en canastilla lateral. Espumador de leche junto al equipo.',
     'On the counter (WiFi router above this machine). Capsules in the side basket. Milk frother next to the machine.'),
    ('Hielera automática', 'Ice maker'),
    ('Junto al refrigerador. Se reabastece en ~30 min tras vaciarse.', 'Next to the refrigerator. Refills in ~30 min after emptying.'),
    ('Licuadora profesional', 'Professional blender'),
    ('Segundo gabinete bajo mostrador (izq. a der.). Enjuaga y devuelve después de usar.',
     'Second cabinet under counter (left to right). Rinse and return after use.'),
    ('Refrigerador y minibar', 'Refrigerator & minibar'),
    ('Agua, jugos y cerveza. Reposición diaria del minibar.', 'Water, juices, and beer. Minibar restocked daily.'),
    ('Lavavajillas', 'Dishwasher'),
    ('Tabletas bajo fregadero. Ciclo Normal ~1 h.', 'Tablets under the sink. Normal cycle ~1 hr.'),
    ('Basura', 'Trash'),
    ('Recolección', 'Pickup'),
    ('lunes, miércoles y viernes', 'Monday, Wednesday, and Friday'),
    ('Bolsas negras obligatorias (debajo del fregadero) para botes exteriores — sin bolsa no recogen.',
     'Black bags required (under the sink) for outdoor bins — no bag means no pickup.'),
    ('Agua e insumos', 'Water & supplies'),
    ('El agua del grifo no es para beber.', 'Tap water is not for drinking.'),
    ('Usa dispensador o garrafón filtrado. Avisar a Cecilia si se agota antes del reabasto.',
     'Use the dispenser or filtered jug. Tell Cecilia if it runs out before restock.'),
    ('Dispensador', 'Water dispenser'),
    ('Agua filtrada para consumo diario en cocina y áreas comunes.',
     'Filtered water for daily use in the kitchen and common areas.'),
    ('Envía tu lista a Marlon — surtimos antes de tu llegada o durante la estancia, a precio de costo con recibo.',
     'Send your list to Marlon — we stock before arrival or during your stay, at cost with receipt.'),
    ('08 · Asador', '07 · Grill'),
    ('Cómo Usar el Asador de Carbón', 'How to use the charcoal grill'),
    ('alt="Asador en terraza con vista al mar"', 'alt="Grill on terrace with ocean view"'),
    ('Asador Weber con chimenea de encendido', 'Weber grill with chimney starter'),
    ('En la terraza principal.', 'On the main terrace.'),
    ('en la cocina de alberca (Cocina 2). Sin combustible líquido.', 'in the pool kitchen (Kitchen 2). No liquid fuel.'),
    ('Guía de temperaturas', 'Temperature guide'),
    ('Alto', 'High'),
    ('Steaks y hamburguesas', 'Steaks & burgers'),
    ('Medio-alto', 'Medium-high'),
    ('Pollo, pescado', 'Chicken, fish'),
    ('Medio', 'Medium'),
    ('Costillas, cerdo', 'Ribs, pork'),
    ('Bajo', 'Low'),
    ('BBQ lento', 'Slow BBQ'),
    ('Cómo encender — 7 pasos', 'Lighting the grill — 7 steps'),
    ('Llena la chimenea ¾ con carbón', 'Fill chimney ¾ with charcoal'),
    ('La bolsa está en el gabinete del asador. No llenes de más.', 'Charcoal is in the pool kitchen. Do not overfill.'),
    ('Coloca los iniciadores debajo', 'Place starters underneath'),
    ('1–2 bloques de cera natural bajo la rejilla de la chimenea. Nunca uses combustible líquido.',
     '1–2 natural wax blocks under the chimney grate. Never use liquid fuel.'),
    ('Pon la chimenea en el asador', 'Set chimney on the grill'),
    ('Todas las ventillas abiertas para buena circulación de aire.', 'All vents open for good airflow.'),
    ('Enciende los iniciadores', 'Light the starters'),
    ('Usa el encendedor largo por los hoyos de abajo. No necesitas meter la mano.',
     'Use the long lighter through the bottom holes. No need to reach inside.'),
    ('Espera 15–20 minutos', 'Wait 15–20 minutes'),
    ('Listo cuando los carbones de arriba brillen naranja con ceniza blanco-grisácea. No apures este paso.',
     'Ready when top coals glow orange with gray-white ash. Do not rush this step.'),
    ('Vierte el carbón y extiende', 'Pour charcoal and spread'),
    ('Usa guantes térmicos. Inclina la chimenea para verter. Extiende parejo con las pinzas. Coloca la parrilla encima.',
     'Use heat gloves. Tilt the chimney to pour. Spread evenly with tongs. Place the grate on top.'),
    ('Precalienta 5 min → ¡A cocinar!', 'Preheat 5 min → cook!'),
    ('Cepilla la parrilla cuando esté caliente. Ya está lista.', 'Brush the grate while hot. Ready to cook.'),
    ('Seguridad:', 'Safety:'),
    ('Nunca uses combustible líquido. Cierra ventillas para apagar. Espera 2 h antes de tocar ceniza. Extinguidor: cocina, compartimiento inferior izquierdo.',
     'Never use liquid fuel. Close vents to extinguish. Wait 2 hrs before touching ash. Fire extinguisher: kitchen, lower left cabinet.'),
    ('Limpieza después de asar', 'Cleanup after grilling'),
    ('Cepilla la parrilla mientras aún está caliente — la grasa fría es mucho más difícil de limpiar',
     'Brush the grate while still hot — cold grease is much harder to clean'),
    ('Cierra todas las ventillas para apagar los carbones', 'Close all vents to extinguish the coals'),
    ('Espera que enfríe completamente (1–2 hrs) antes de mover la ceniza',
     'Wait until fully cool (1–2 hrs) before moving ash'),
    ('Desecha la ceniza fría en el cubo metálico junto al asador — nunca en bolsas de plástico',
     'Dispose of cold ash in the metal bin by the grill — never in plastic bags'),
    ('06 · Exteriores', '08 · Outdoors'),
    ('Terraza, alberca y playa', 'Terrace, pool & beach'),
    ('Escaleras a la alberca:', 'Pool stairs:'),
    ('Ten cuidado al bajar — hay un cambio de nivel pronunciado. Usa el pasamanos y calzado antiderrapante.',
     'Use caution going down — there is a significant level change. Use the handrail and non-slip footwear.'),
    ('Alberca y chapoteadero', 'Pool & splash pad'),
    ('1.2 m – 1.8 m de profundidad', '1.2 m – 1.8 m depth'),
    ('Toallas en gabinete junto a regadera exterior', 'Towels in cabinet by outdoor shower'),
    ('Luces automáticas al anochecer', 'Lights turn on automatically at dusk'),
    ('Cero vidrio', 'No glass'),
    ('en el área — solo plástico', 'in the area — plastic only'),
    ('Reja cerrada cuando haya niños', 'Keep gate closed when children are present'),
    ('No clavados — alberca no calentada', 'No diving — pool is not heated'),
    ('Servicio: cada viernes', 'Service: every Friday'),
    ('Splash pool (niños)', 'Splash pad (kids)'),
    ('Agua poco profunda · chapoteadero', 'Shallow water · splash pad'),
    ('Pensada para niños; un adulto responsable debe supervisar siempre',
     'Designed for children; a responsible adult must supervise at all times'),
    ('No es para nadar ni zambullirse — evita correr en los bordes mojados',
     'Not for swimming or diving — avoid running on wet edges'),
    ('Juguetes plásticos y flotadores están bien; nada de vidrio en el área',
     'Plastic toys and floats are fine; no glass in the area'),
    ('Misma zona exterior que la alberca: mantén la reja cerrada si hay pequeños cerca del agua',
     'Same outdoor area as the pool: keep the gate closed if children are near the water'),
    ('Si notas filtro o agua turbia, avisa a Marlon o a tu equipo de casa',
     'If the filter or water looks cloudy, tell Marlon or your house team'),
    ('Jacuzzi — apagado obligatorio', 'Jacuzzi — mandatory shut-off'),
    ('Al terminar de usarlo', 'When finished'),
    ('Entra a', 'Go to'),
    ('Recámara 2', 'Bedroom 2'),
    ('A mano derecha, apaga la caldera', 'On the right, turn off the heater unit'),
    ('Apaga', 'Turn off'),
    ('Playa privada', 'Private beach'),
    ('Acceso exclusivo', 'Guests only'),
    ('Escaleras de piedra a la derecha de la villa', 'Stone stairs on the right side of the villa'),
    ('Regadera de enjuague arriba, al inicio de la escalera', 'Freshwater rinse shower at the top of the stairs'),
    ('Camastros, sombrilla y snorkel al pie', 'Loungers, umbrella, and snorkel gear at the bottom'),
    ('Beach disclaimer:', 'Beach disclaimer:'),
    ('La playa es nadable, pero el Mar de Cortés es complejo. El nado es bajo tu propio riesgo y discreción. Consulta condiciones con Marlon.',
     'The beach is swimmable, but the Sea of Cortés can be complex. Swimming is at your own risk and discretion. Check conditions with Marlon.'),
    ('09 · Servicios premium', '09 · Premium services'),
    ('Eleva tu estancia', 'Elevate your stay'),
    ('Experiencias que diseñamos contigo, con tiempo, discreción y un estándar muy alto.',
     'Experiences we design with you — unhurried, discreet, and held to a very high standard.'),
    ('Coordinación directa con Marlon · inversión según servicio · WhatsApp',
     'Coordinated directly with Marlon · pricing per experience · WhatsApp'),
    ('Chef Privado', 'Private Chef'),
    ('Menús con ingredientes locales frescos. Desayuno, comida o cenas privadas. Servicio completo incluyendo montaje y limpieza.',
     'Menus with fresh local ingredients. Breakfast, lunch, or private dinners. Full service including setup and cleanup.'),
    ('Solicitar vía WhatsApp →', 'Request via WhatsApp →'),
    ('Yate Privado', 'Private Yacht'),
    ('Tours al Arco, snorkel, pesca deportiva, avistamiento de ballenas (temporada) y cruceros al atardecer. Medio o día completo.',
     'Arch tours, snorkeling, sport fishing, whale watching (season), and sunset cruises. Half or full day.'),
    ('Spa y Masajes', 'Spa & Massages'),
    ('Terapeutas certificados en la villa. Sueco, tejido profundo, piedras calientes, masaje de pareja, faciales, manicure y pedicure.',
     'Certified therapists at the villa. Swedish, deep tissue, hot stone, couples massage, facials, manicure, and pedicure.'),
    ('Deportes Acuáticos', 'Water Sports'),
    ('Paddle board, kayak, snorkel, parasailing, clases de surf y Jet Ski. Equipo entregado en la playa o la villa.',
     'Paddle board, kayak, snorkeling, parasailing, surf lessons, and Jet Ski. Equipment delivered to the beach or villa.'),
    ('Transporte de Lujo', 'Luxury Transport'),
    ('SUV privado, tour en helicóptero sobre el Arco, jets privados y traslados VIP al aeropuerto. Reserva anticipada requerida.',
     'Private SUV, helicopter tour over the Arch, private jets, and VIP airport transfers. Advance booking required.'),
    ('Eventos Privados', 'Private Events'),
    ('Bodas, cumpleaños, propuestas, despedidas de soltero y retiros corporativos. Coordinación completa: flores, catering, DJ, fotografía.',
     'Weddings, birthdays, proposals, bachelor parties, and corporate retreats. Full coordination: flowers, catering, DJ, photography.'),
    ('Golf', 'Golf'),
    ('Tee times en Quivira, El Camaleón y Palmilla — campos de clase mundial. Renta de palos, caddies y transporte incluidos.',
     'Tee times at Quivira, El Camaleón, and Palmilla — world-class courses. Club rental, caddies, and transport included.'),
    ('Yoga y Fitness', 'Yoga & Fitness'),
    ('Clases privadas de yoga al amanecer en la terraza o playa. Entrenador personal, instructor de Pilates o guía de meditación.',
     'Private sunrise yoga on the terrace or beach. Personal trainer, Pilates instructor, or meditation guide.'),
    ('Servicio de Compras', 'Grocery Service'),
    ('Envíale tu lista a Marlon y surtimos la villa antes de tu llegada o durante la estancia. Se cobra a precio de costo con recibo.',
     'Send your list to Marlon and we stock the villa before arrival or during your stay. Charged at cost with receipt.'),
    ('Si es importante para ti, es importante para nosotros.', 'If it matters to you, it matters to us.'),
    ('08 · Guía local', '10 · Local guide'),
    ('Guía local', 'Local guide'),
    ('Amenidades incluidas, comercios cercanos y restaurantes del momento — Marlon gestiona reservas.',
     'Included amenities, nearby shops, and current restaurants — Marlon handles reservations.'),
    ('Amenidades incluidas:', 'Included amenities:'),
    ('Jabón de baño, body wash, body lotion, shampoo y acondicionador en todas las suites y baños.',
     'Bath soap, body wash, body lotion, shampoo, and conditioner in all suites and bathrooms.'),
    ('Comercios de proximidad', 'Nearby essentials'),
    ('12 min en auto', '12 min by car'),
    ('10 min en auto', '10 min by car'),
    ('15 min en auto', '15 min by car'),
    ('Farmacias del Ahorro · 24 hrs con médico', 'Farmacias del Ahorro · 24 hrs with doctor'),
    ('8 min en auto', '8 min by car'),
    ('La Europea · vinos y licores', 'La Europea · wine & spirits'),
    ('Restaurantes del momento', 'Restaurants of the moment'),
    ('Selección detallada', 'Curated picks'),
    ('Mariscos modernos · One&Only Palmilla. Reserva con anticipación.', 'Modern seafood · One&Only Palmilla. Book ahead.'),
    ('15 min · Vía Marlon', '15 min · Via Marlon'),
    ('Waldorf Pedregal · pescado en tanque vivo sobre el acantilado.', 'Waldorf Pedregal · live fish tank dining on the cliff.'),
    ('Vista legendaria al Arco · cena especial al atardecer.', 'Legendary Arch view · special sunset dinner.'),
    ('Sashimi y rolls de autor · Centro Marina.', 'Iconic sashimi and creative rolls · Marina center.'),
    ("Clásico cabense de mariscos y ambiente relajado — muy pedido por locales y huéspedes.",
     "Beloved local seafood spot with a relaxed vibe — popular with guests and locals."),
    ('Ambiente contemporáneo y cocina de Baja — favoritos actuales del destino.',
     'Contemporary vibe and Baja cuisine — current destination favorites.'),
    ('Vía concierge', 'Via concierge'),
    ('No te pierdas', 'Do not miss'),
    ('El Arco', 'The Arch'),
    ('taxi acuático desde la marina (~$15 USD) o tour privado vía Marlon',
     'water taxi from the marina (~$15 USD) or private tour via Marlon'),
    ('Pesca deportiva', 'Sport fishing'),
    ('marlín, atún y dorado de clase mundial. Salen a las 6 AM. Tu pesca la prepara el chef.',
     'world-class marlin, tuna, and dorado. Boats leave at 6 AM. Your catch can be prepared by the chef.'),
    ('Art Walk San José', 'Art Walk San José'),
    ('cada jueves (nov–jun). Galerías, música y comida callejera en el centro histórico.',
     'every Thursday (Nov–Jun). Galleries, music, and street food in the historic center.'),
    ('Todos Santos', 'Todos Santos'),
    ('Pueblo Mágico, 1 hr al norte. El legendario Hotel California y mezcal artesanal.',
     'Magic Town, 1 hr north. The legendary Hotel California and artisanal mezcal.'),
    ('Avistamiento de ballenas', 'Whale watching'),
    ('temporada dic–abr. Uno de los mejores lugares del mundo.',
     'season Dec–Apr. One of the best places in the world.'),
    ('10 · Emergencias', '11 · Emergencies'),
    ('Todo lo que Necesitas Saber', 'Everything you need'),
    ('Cómo moverse', 'Getting around'),
    ('Ambas apps funcionan en Los Cabos. Descárgalas antes de llegar. Más baratas y seguras que los taxis de calle.',
     'Both apps work in Los Cabos. Download before you arrive. Cheaper and safer than street taxis.'),
    ('Chofer privado (recomendado)', 'Private driver (recommended)'),
    ('Marlon coordina choferes confiables de habla inglesa. Ideal para excursiones a Todos Santos o San José.',
     'Marlon arranges reliable English-speaking drivers. Ideal for Todos Santos or San José trips.'),
    ('Renta de auto', 'Car rental'),
    ('Licencias internacionales aceptadas. Hertz y Alamo en el aeropuerto. Recomendado: SUV compacta.',
     'International licenses accepted. Hertz and Alamo at the airport. Recommended: compact SUV.'),
    ('Esenciales cercanos', 'Nearby essentials'),
    ('Supermercado La Comer', 'La Comer supermarket'),
    ('El mejor súper. Productos internacionales, vinos y licores. Plaza Las Glorias.',
     'Best grocery store. International products, wine, and spirits. Plaza Las Glorias.'),
    ('Farmacia 24 horas con médico de guardia (~$5 USD).', '24-hour pharmacy with on-call doctor (~$5 USD consult).'),
    ('Mejor selección de vinos, espirituales y productos importados. Plaza Las Glorias.',
     'Best selection of wine, spirits, and imported goods. Plaza Las Glorias.'),
    ('Datos útiles', 'Useful facts'),
    ('Moneda: Peso mexicano (MXN) · Dólares aceptados ampliamente · Propina: 15–20% en restaurantes · Zona horaria: MST UTC-7 · Voltaje: 110V enchufes tipo americano',
     'Currency: Mexican peso (MXN) · US dollars widely accepted · Tip: 15–20% at restaurants · Time zone: MST UTC-7 · Voltage: 110V US-style outlets'),
    ('Contactos de emergencia', 'Emergency contacts'),
    ('House Manager · Primer contacto', 'House Manager · First contact'),
    ('Marlon Alexis Herrera. Emergencias y coordinación — respuesta prioritaria.',
     'Marlon Alexis Herrera. Emergencies and coordination — priority response.'),
    ('Policía · Bomberos · Emergencias', 'Police · Fire · Emergency'),
    ('Servicio de emergencias general. Igual que en EE.UU. / Canadá.', 'General emergency service. Same as US / Canada.'),
    ('Hospital H+ Los Cabos · Recomendado', 'H+ Hospital Los Cabos · Recommended'),
    ('Mejor hospital privado. Urgencias 24 hrs. Médicos de habla inglesa.', 'Leading private hospital. 24-hour ER. English-speaking physicians.'),
    ('15 min en auto', '15 min by car'),
    ('Cruz Roja · Ambulancia', 'Red Cross · Ambulance'),
    ('Servicio de ambulancia de Los Cabos.', 'Los Cabos ambulance service.'),
    ('Farmacia del Ahorro · 24 hrs', 'Farmacia del Ahorro · 24 hrs'),
    ('Farmacia con médico de guardia. Rápida para emergencias menores.', 'Pharmacy with on-call doctor. Fast for minor emergencies.'),
    ('Equipo de seguridad en la villa', 'Safety equipment in the villa'),
    ('Extinguidor: gabinete cocina, compartimiento inferior izquierdo', 'Fire extinguisher: kitchen cabinet, lower left compartment'),
    ('Botiquín: baño de la suite master, repisa superior', 'First aid kit: master suite bathroom, upper shelf'),
    ('Salvavidas: gabinete de alberca, panel derecho', 'Life ring: pool cabinet, right panel'),
    ('Caja fuerte: clóset de la suite master — código te lo da Marlon al llegar',
     'Safe: master suite closet — Marlon provides the code at arrival'),
    ('09 · Salida', '12 · Check-out'),
    ('Antes de partir · 12:00 PM', 'Before you leave · 12:00 PM'),
    ('Reglamento de la villa', 'House rules'),
    ('No fumar dentro de la villa. Área de fumadores en la terraza exterior únicamente.',
     'No smoking inside the villa. Smoking area on the outdoor terrace only.'),
    ('No se aceptan mascotas sin autorización previa por escrito.', 'No pets without prior written approval.'),
    ('Máximo 8 huéspedes por noche. Visitas diurnas con aviso previo.', 'Maximum 8 guests per night. Day visitors with advance notice.'),
    ('Eventos o fiestas requieren autorización — silencio en exteriores desde las 11:00 PM.',
     'Events or parties require approval — quiet outdoors from 11:00 PM.'),
    ('La playa privada es exclusiva para huéspedes de Villa Sera.', 'The private beach is for Villa Sera guests only.'),
    ('Reporta cualquier daño inmediatamente — los accidentes se entienden, la honestidad se agradece.',
     'Report any damage immediately — accidents happen, honesty is appreciated.'),
    ('No tire toallitas húmedas ni productos higiénicos al inodoro — use botes de basura.',
     'Do not flush wet wipes or hygiene products — use trash bins.'),
    ('Sin vidrio en el área de alberca o splash pool — se proporcionan vasos de plástico.',
     'No glass in the pool or splash pad area — plastic cups provided.'),
    ('Apague el jacuzzi (Recámara 2) al terminar de usarlo — Jets y Heater.',
     'Turn off the jacuzzi (Bedroom 2) when finished — Jets and Heater.'),
    ('Niños siempre supervisados cerca del agua — sin excepción.', 'Children always supervised near water — no exceptions.'),
    ('Apaga todos los ACs y luces al salir de la villa.', 'Turn off all AC units and lights when leaving the villa.'),
    ('No muevas ni saques el mobiliario de la propiedad.', 'Do not move or remove furniture from the property.'),
    ('Cubre la caminadora después de cada uso — el salitre daña la banda.', 'Cover the treadmill after each use — salt air damages the belt.'),
    ('Cierra sesión en tus cuentas de streaming en todos los televisores al hacer check-out.',
     'Sign out of streaming accounts on all TVs at check-out.'),
    ('Check-out · Lista — antes de las 12:00 PM', 'Check-out · checklist — by 12:00 PM'),
    ('Devuelve llaves, controles de TV, AC, reja de alberca y garage',
     'Return keys, TV remotes, AC remotes, pool gate remote, and garage remote'),
    ('Apaga todos los ACs, jacuzzi (Rec. 2) y aparatos eléctricos',
     'Turn off all AC, jacuzzi (Bed. 2), and appliances'),
    ('Cierra ventanas, puertas y terrazas (hermeticidad)', 'Close windows, doors, and terraces (sealed)'),
    ('Cierra sesión de streaming en todas las TCL', 'Sign out of streaming on all TCL TVs'),
    ('Cubre la caminadora con su funda impermeable', 'Cover treadmill with waterproof cover'),
    ('Basura en botes exteriores con bolsas negras', 'Trash in outdoor bins with black bags'),
    ('Revisa que no queden pertenencias en clósets o caja fuerte', 'Check closets and safe for belongings'),
    ('Avisa a Marlon por WhatsApp cuando estés listo para salir', 'Message Marlon on WhatsApp when ready to leave'),
    ('Gracias por quedarte en', 'Thank you for staying at'),
    ('"Que el mar, la luz y la calma de este rincón te acompañen mucho después de haber cerrado la puerta."',
     '"May the sea, the light, and the calm of this place stay with you long after you close the door."'),
    ('Los Cabos · México · A Sera Holding Property', 'Los Cabos · Mexico · A Sera Holding Property'),
]

for old, new in pairs:
    s = s.replace(old, new)

path.write_text(s, encoding="utf-8")
print("Translated", len(pairs), "strings")
